name: CD Infra (Terraform)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write      # Required for OIDC
  contents: read

jobs:

  # ================= DEV DEPLOY =================

  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (DEV)
        run: terraform init
        working-directory: envs/dev

      - name: Terraform Apply (DEV)
        run: terraform apply -auto-approve
        working-directory: envs/dev


  # ================= TEST DEPLOY =================

  deploy-test:
    name: Deploy TEST
    runs-on: ubuntu-latest
    needs: deploy-dev     # Runs only after DEV success

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (TEST)
        run: terraform init
        working-directory: envs/test

      - name: Terraform Apply (TEST)
        run: terraform apply -auto-approve
        working-directory: envs/test


  # ================= PROD DEPLOY =================

  deploy-prod:
    name: Deploy PROD
    runs-on: ubuntu-latest
    needs: deploy-test    # Runs only after TEST success

    environment: production   # Enables GitHub environment protection (optional)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (PROD)
        run: terraform init
        working-directory: envs/prod

      - name: Terraform Apply (PROD)
        run: terraform apply -auto-approve
        working-directory: envs/prod
